name: my workflow
on: workflow_dispatch
jobs:
 debug:
   runs-on: ubuntu-latest
   steps:
     - name: Let debug
       run: echo "welcome to github actions One"

 test:
   runs-on: ubuntu-latest
   steps:
     - name: let test
       run: echo "WE have tested your application"
      
